adapters:
  - http
  - ws
  - reverse-ws
debug: true
port: 8080
authKey: "xiaoyou-bot"
enableVerify: false
verifyKey: "xiaoyou-verify"

# 反向WebSocket配置
reverseWebsocket:
  - enabled: true
    reverseUrl: "ws://127.0.0.1:8080/qq/ws"
    reverseApiUrl: "ws://127.0.0.1:8080/qq/api"
    reverseEventUrl: "ws://127.0.0.1:8080/qq/event"
    reconnectInterval: 3000

# HTTP配置
http:
  host: "0.0.0.0"
  port: 8080
  cors: ["*"]

# WebSocket配置
ws:
  host: "0.0.0.0"
  port: 8080
  reservedSyncId: -1